### ISSUE TITLE
Exception pooing out over this line can you look on it

### ISSUE THREAD

**Issue by ergauravsethi376** [masihyeganeh/YoutubeDownloader#56] opened 2018-11-03 07:37 UTC
https://github.com/masihyeganeh/YoutubeDownloader/blob/5b9e0b08713639223fac0208901240d4867d3abd/Masih/YoutubeDownloader/YoutubeDownloader.php#L500

**Comment by masihyeganeh** [comment] 2018-11-03 08:40
Duplicate of #55

**Closed by masihyeganeh** 2018-11-03 08:40 UTC
Labels: duplicate
